Update delete_aws_resource.yml

diff --git a/.github/workflows/delete_aws_resource.yml b/.github/workflows/delete_aws_resource.yml
--- a/.github/workflows/delete_aws_resource.yml
+++ b/.github/workflows/delete_aws_resource.yml
@@ -1,12 +1,10 @@
 name: Terraform Destroy
 
 on:
-  push:
-    branches:
-      - main
+  workflow_dispatch:
 
 jobs:
-  deploy:
+  destroy:
     runs-on: ubuntu-latest
 
     steps:
@@ -26,9 +24,15 @@ jobs:
       - name: Run AWS Destroy Script
         run: |
           echo "⚠️ Running AWS Destroy Script"
-          ./aws-nuke-us-east-1.sh
+          ./aws-nuke-us-east-1.sh || true  # prevent job failure if destroy script fails
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
-        continue-on-error: true
+
+      - name: Terraform Destroy
+        run: terraform destroy -auto-approve
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: us-east-1
